services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: college-management-demo/php:latest
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - vendor:/var/www/vendor
      - storage:/var/www/storage
      - bootstrap-cache:/var/www/bootstrap/cache
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: college-management-demo/nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "${APP_PORT:-8080}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
    image: college-management-demo/mysql:5.7.22
    restart: unless-stopped
    tty: true
    ports:
      - "${DB_PORT:-3307}:3306"
    environment:
      MYSQL_DATABASE: unifiedtransform
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - "${MYSQL_DATA_DIR:-./docker-data/unifiedtransform/mysql}:/var/lib/mysql"
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

volumes:
  vendor:
  storage:
  bootstrap-cache:
